//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server_QLTraSua.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }

        //[global::System.Configuration.ApplicationScopedSettingAttribute()]
        //[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        //[global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        //[global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-TGUNJQL\\SQLEXPRESS;Initial Catalog=QLBanTraSua;User ID=sa;Pas" +
        //    "sword=system")]
        //public string QLBanTraSuaConnectionString {
        //    get {
        //        return ((string)(this["QLBanTraSuaConnectionString"]));
        //    }
        //}

        //[global::System.Configuration.ApplicationScopedSettingAttribute()]
        //[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        //[global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        //[global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-TGUNJQL\\SQLEXPRESS;Initial Catalog=QLBanTraSua;Persist Securi" +
        //    "ty Info=True;User ID=sa;Password=system")]
        //public string QLBanTraSuaConnectionString1 {
        //    get {
        //        return ((string)(this["QLBanTraSuaConnectionString1"]));
        //    }
        //}

        //[global::System.Configuration.ApplicationScopedSettingAttribute()]
        //[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        //[global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        //[global::System.Configuration.DefaultSettingValueAttribute("Data Source=NICK-LAPTOP\\SQLEXPRESS;Initial Catalog=QLBanTraSua;User ID=sa;Passwor" +
        //    "d=system")]
        //public string QLBanTraSuaConnectionString2 {
        //    get {
        //        return ((string)(this["QLBanTraSuaConnectionString2"]));
        //    }
        //}

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;Initial Catalog=QLQuanTS;User ID=sa;Password=system")]
        public string QLQuanTSConnectionString
        {
            get
            {
                return ((string)(this["QLQuanTSConnectionString"]));
            }
        }
    }
}
